//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curso
    {
        public Curso()
        {
            this.Aluno = new HashSet<Aluno>();
            this.Disciplina = new HashSet<Disciplina>();
        }
    
        public int cursoID { get; set; }
        public string nome { get; set; }
        public int universidadeID { get; set; }
    
        public virtual ICollection<Aluno> Aluno { get; set; }
        public virtual Universidade Universidade { get; set; }
        public virtual ICollection<Disciplina> Disciplina { get; set; }
    }
}
