//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disciplina
    {
        public Disciplina()
        {
            this.Notas = new HashSet<Notas>();
        }
    
        public int disciplinaID { get; set; }
        public int cursoID { get; set; }
        public string nome { get; set; }
    
        public virtual Curso Curso { get; set; }
        public virtual ICollection<Notas> Notas { get; set; }
    }
}
